-- ==========================================
-- STEP 1: RUN AS SYSDBA
-- ==========================================
-- Create the dedicated application user and grant permissions
-- (Make sure you are connected to the pluggable database FREEPDB1)

-- CREATE USER CALCULATOR_USER IDENTIFIED BY Password123;
-- GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO CALCULATOR_USER;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO CALCULATOR_USER;


-- ==========================================
-- STEP 2: CONNECT AS CALCULATOR_USER AND RUN
-- ==========================================

-- Create Sequence for Calculation History
CREATE SEQUENCE CALCULATION_HISTORY_SEQ START WITH 1 INCREMENT BY 1;

-- Create Table CALCULATION_HISTORY
CREATE TABLE CALCULATION_HISTORY (
    ID NUMBER(19, 0) DEFAULT CALCULATION_HISTORY_SEQ.NEXTVAL PRIMARY KEY,
    MESSAGE_ID VARCHAR2(50) NOT NULL,
    CORRELATION_ID VARCHAR2(50) NOT NULL,
    CONSUMER_TYPE VARCHAR2(50) NOT NULL,
    CLIENT_ID VARCHAR2(50) NOT NULL,
    OPERAND1 NUMBER(38, 10) NOT NULL,
    OPERAND2 NUMBER(38, 10) NOT NULL,
    OPERATION VARCHAR2(20) NOT NULL,
    RESULT_VALUE NUMBER(38, 10) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create Sequence for Calculation Error Log
CREATE SEQUENCE CALCULATION_ERROR_LOG_SEQ START WITH 1 INCREMENT BY 1;

-- Create Table CALCULATION_ERROR_LOG
CREATE TABLE CALCULATION_ERROR_LOG (
    ID NUMBER(19, 0) DEFAULT CALCULATION_ERROR_LOG_SEQ.NEXTVAL PRIMARY KEY,
    MESSAGE_ID VARCHAR2(50),
    CORRELATION_ID VARCHAR2(50),
    CONSUMER_TYPE VARCHAR2(50),
    CLIENT_ID VARCHAR2(50),
    ERROR_CODE VARCHAR2(10) NOT NULL,
    ERROR_MESSAGE VARCHAR2(255) NOT NULL,
    ERROR_DETAILS VARCHAR2(4000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
